### ISSUE TITLE
Templates dir path not exists

### ISSUE THREAD

**Issue by nandinichaurasiya** [COVESA/vsc-tools#43]
Heading: Simple Generator 
[vsc/templates/ dir](https://github.com/COVESA/vsc-tools/blob/master/templates)
This path mentioned in README.md file, doesn't exist.

**Comment by gunnarx** [comment]
Thanks for checking.  Is your directory fully up to date?  
Because I think it is there in the latest master branch. See link: 
https://github.com/COVESA/vsc-tools/tree/master/vsc/templates

**Comment by erikbosch** [comment]
The text in the README was correct but the link was not. Added a PR.

`[vsc/templates/ dir](templates)`
