### ISSUE TITLE
[VSC] More/final discussion of Command/Method/Event definitions.  Are they appropriately defined?

### ISSUE THREAD

**Issue by gunnarx** [COVESA/vsc-tools#5]
Question 1 - is it required to have separate names for Command and Method, when one seems just a subset of the other?

Question 2 - should events have full function signatures as in the current example.  This must be discussed together with the Events discussion in VSS.

**Comment by gunnarx** [comment]
This is actually a "VSC" format question...

**Comment by magnusfeuer** [comment]
I will collapse Command into Method, leaving only Method in place.

**Comment by gunnarx** [comment]
This was an issue that should have been in the [VSC definition itself ](https://github.com/COVESA/vehicle_service_specification).  In any case, I think it is resolved, so closing.
